app:
  application-name: inventory # change
  server-port: 8083 # change
  application-version: v1
  context-path: api/${app.application-name}/${app.application-version}
  database-hostname: localhost # change
  database-port: 5434 # change
  database-name: ${app.application-name}_service_${app.application-version}
  eureka-hostname: localhost # change
  eureka-port: 8761
  keycloak-host: localhost # change
  keycloak-port: 8090
  api-gateway-hostname: localhost # change
  swagger-api-gateway-hostname: localhost # change
  api-gateway-server-port: 8181
  swagger-info-title: Inventory Service # change
  swagger-info-version: v1.0 # change
  zipkin-hostname: localhost
  zipkin-server-port: 9411
  zipkin-context-path: api/v2/spans
  zipkin-endpoint: http://${app.zipkin-hostname}:${app.zipkin-server-port}/${app.zipkin-context-path}
  #kafka
  kafka-hostname: localhost
  kafka-port: 9092
  kafka-default-topic: default-topic
  kafka-default-concurrency: 3
  kafka-default-group-id: default-group-id

security:
  enabled: true
  skip-urls:
    - /guest/**
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api-docs/**
    - /error/**

spring:
  application:
    name: ${app.application-name}-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.keycloak-host}:${app.keycloak-port}/realms/spring-boot-microservices-realm
  datasource:
    url: jdbc:postgresql://${app.database-hostname}:${app.database-port}/${app.database-name}
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: classpath:db/migration/
    validate-on-migrate: true
    enabled: true
    table: schema_history
  kafka:
    enabled: true
    bootstrap-servers: ${app.kafka-hostname}:${app.kafka-port}
    template:
      default-topic: ${app.kafka-default-topic}
      default-group-id: ${app.kafka-default-group-id}
      properties:
        default-concurrency: ${app.kafka-default-concurrency}
    #    producers:
    #      test-topic:
    #        topic-name: test-topic
    #      order-pending:
    #        topic-name: order-pending

    consumers:
      test-topic:
        topic-name: test-topic
        group-id: test-topic-${spring.application.name}
        properties:
          concurrency: ${app.kafka-default-concurrency}
  #      order-item-not-available:
  #        topic-name: order-item-not-available
  #        group-id: order-item-not-available-${spring.application.name}
  #        properties:
  #          concurrency: ${app.kafka-default-concurrency}
  #      order-processing:
  #        topic-name: order-processing
  #        group-id: order-processing-${spring.application.name}
  #        properties:
  #          concurrency: ${app.kafka-default-concurrency}
  #      order-payment-processing:
  #        topic-name: order-payment-processing
  #        group-id: order-payment-processing-${spring.application.name}
  #        properties:
  #          concurrency: ${app.kafka-default-concurrency}

server:
  port: ${app.server-port}
  servlet:
    context-path: /${app.context-path}



eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-hostname}:${app.eureka-port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    root: INFO
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  server:
    url: http://${app.swagger-api-gateway-hostname}:${app.api-gateway-server-port}/${app.context-path}
  info:
    title: ${app.swagger-info-title}
    version: ${app.swagger-info-version}
    description: Documentation ${app.swagger-info-title} ${app.swagger-info-version}
#  security-scheme:
#    name: bearerAuth
#    bearer-format: JWT
#    scheme: bearer

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always


management:
  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${app.zipkin-endpoint}
